site_name: Kube-OVN 文档
site_author: Kube-OVN Team
repo_name: kubeovn/kube-ovn
repo_url: https://github.com/kubeovn/kube-ovn/
edit_uri: ../docs/edit/master/docs/
nav:
  - 主页: 'index.md'
  - 快速入门:
      - 准备工作: 'start/prepare.md'
      - 一键安装: 'start/one-step-install.md'
      - Underlay 网络安装: 'start/underlay.md'
      - 卸载: 'start/uninstall.md'
  - 使用指南:
      - 安装和配置选项: 'guide/setup-options.md'
      - 固定地址: 'guide/static-ip-mac.md'
      - 子网使用: 'guide/subnet.md'
      - VPC 使用: 'guide/vpc.md'
      - 容器网络 QoS 配置: 'guide/qos.md'
      - 配置监控和面板: 'guide/prometheus-grafana.md'
      - 双栈使用: 'guide/dual-stack.md'
      - EIP 和 SNAT 配置: 'guide/eip-snat.md'
      - 流量镜像: 'guide/mirror.md'
      - Webhook 使用: 'guide/webhook.md'
  - 运维指南:
      - kubectl 插件使用: 'ops/kubectl-ko.md'
      - 删除工作节点: 'ops/delete-worker-node.md'
      - 更换 ovn-central 节点: 'ops/change-ovn-central-node.md'
      - OVN 数据库备份和恢复: 'ops/recover-db.md'
      - 修改子网 CIDR: 'ops/change-default-subnet.md'
      - 修改 Join 子网 CIDR: 'ops/change-join-subnet.md'
      - 卸载 Calico 安装 Kube-OVN: 'ops/from-calico.md'
      - 其他常见问题: 'ops/faq.md'
  - 高级功能:
      - 多网卡管理: 'advance/multi-nic.md'
      - 性能调优: 'advance/performance-tuning.md'
      - 手动编译 FastPath 模块: 'advance/fastpath.md'
      - 使用 OVN-IC 进行多集群互联: 'advance/with-ovn-ic.md'
      - 使用 Submariner 进行多集群互联: 'advance/with-submariner.md'
      - BGP 支持: 'advance/with-bgp.md'
      - Cilium 集成: 'advance/with-cilium.md'
      - DHCP 设置: 'advance/dhcp.md'
      - VPC 互联: 'advance/vpc-peering.md'
      - 外部网关设置: 'advance/external-gateway.md'
      - VIP 预留设置: 'advance/vip.md'
      - Mellanox 网卡 Offload 支持: 'advance/offload-mellanox.md'
      - 芯启源网卡 Offload 支持: 'advance/offload-corigine.md'
      - Windows 支持: 'advance/windows.md'
      - DPDK 支持: 'advance/dpdk.md'
      - OpenStack 集成: 'advance/with-openstack.md'
  - 技术参考:
      - 总体架构: 'reference/architecture.md'
      - Underlay 流量拓扑: 'reference/underlay-topology.md'
      - 开发环境构建: 'reference/dev-env.md'
#      - API 指南: 'reference/api.md'
      - 对上游 OVS/OVN 修改: 'reference/ovs-ovn-customized.md'
      - 隧道协议说明: 'reference/tunnel-protocol.md'
      - Kube-OVN 监控指标: 'reference/metrics.md'
  - 联系方式: 'contact.md'
theme:
    name: material
    language: 'zh'
    palette:
      scheme: default
    features:
      - navigation.tabs
markdown_extensions:
  - footnotes
  - fenced_code
plugins:
  - search:
      separator: '[\s\u200b\-]'
#  - with-pdf:
#      author: Kube-OVN Team
#      cover_subtitle: v1.10.1
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/kubeovn
    - icon: fontawesome/brands/github
      link: https://github.com/kubeovn
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/kubeovn/kube-ovn
    - icon: fontawesome/brands/slack
      link: https://kube-ovn-slackin.herokuapp.com/
copyright: Copyright &copy; 2022 The Linux Foundation
