site_name: Kube-OVN 文档
site_author: Kube-OVN Team
repo_name: kubeovn/kube-ovn
repo_url: https://github.com/kubeovn/kube-ovn/
edit_uri: ../docs/edit/master/docs/
nav:
  - 主页: 'index.md'
  - 快速入门:
      - 准备工作: 'start/prepare.md'
      - 一键安装: 'start/one-step-install.md'
      - Underlay 网络安装: 'start/underlay.md'
      - 卸载: 'start/uninstall.md'
  - 使用指南:
      - 安装和配置选项: 'guide/setup-options.md'
      - 固定地址: 'guide/static-ip-mac.md'
      - 子网使用: 'guide/subnet.md'
      - LoadBalancer 类型 Service: 'guide/loadbalancer-service.md'
      - VPC 使用: 'guide/vpc.md'
      - 容器网络 QoS 配置: 'guide/qos.md'
      - 配置监控和面板: 'guide/prometheus-grafana.md'
      - 双栈使用: 'guide/dual-stack.md'
      - EIP 和 SNAT 配置: 'guide/eip-snat.md'
      - 流量镜像: 'guide/mirror.md'
      - NetworkPolicy 日志: 'guide/networkpolicy-log.md'
      - Webhook 使用: 'guide/webhook.md'
  - 运维指南:
      - kubectl 插件使用: 'ops/kubectl-ko.md'
      - 删除工作节点: 'ops/delete-worker-node.md'
      - 更换 ovn-central 节点: 'ops/change-ovn-central-node.md'
      - OVN 数据库备份和恢复: 'ops/recover-db.md'
      - 修改子网 CIDR: 'ops/change-default-subnet.md'
      - 修改 Join 子网 CIDR: 'ops/change-join-subnet.md'
      - 卸载 Calico 安装 Kube-OVN: 'ops/from-calico.md'
      - 其他常见问题: 'ops/faq.md'
  - 高级功能:
      - 多网卡管理: 'advance/multi-nic.md'
      - 性能调优: 'advance/performance-tuning.md'
      - 手动编译 FastPath 模块: 'advance/fastpath.md'
      - 使用 OVN-IC 进行多集群互联: 'advance/with-ovn-ic.md'
      - 使用 Submariner 进行多集群互联: 'advance/with-submariner.md'
      - Overlay 下路由方式网络打通: 'advance/overlay-with-route.md'
      - BGP 支持: 'advance/with-bgp.md'
      - Cilium 集成: 'advance/with-cilium.md'
      - Cilium NetworkPolicy 支持: 'advance/cilium-networkpolicy.md'
      - Cilium 网络流量观测: 'advance/cilium-hubble-observe.md'
      - DHCP 设置: 'advance/dhcp.md'
      - VPC 互联: 'advance/vpc-peering.md'
      - 外部网关设置: 'advance/external-gateway.md'
      - VIP 预留设置: 'advance/vip.md'
      - Mellanox 网卡 Offload 支持: 'advance/offload-mellanox.md'
      - 芯启源网卡 Offload 支持: 'advance/offload-corigine.md'
      - Windows 支持: 'advance/windows.md'
      - DPDK 支持: 'advance/dpdk.md'
      - OpenStack 集成: 'advance/with-openstack.md'
  - 技术参考:
      - 总体架构: 'reference/architecture.md'
      - Underlay 流量拓扑: 'reference/underlay-topology.md'
      - 开发环境构建: 'reference/dev-env.md'
      - 对上游 OVS/OVN 修改: 'reference/ovs-ovn-customized.md'
      - 隧道协议说明: 'reference/tunnel-protocol.md'
      - Kube-OVN 监控指标: 'reference/metrics.md'
      - 文档规范: 'reference/document-convention.md'
  - 联系方式: 'contact.md'
theme:
    name: material
    custom_dir: overrides
    language: 'zh'
    palette:
      - scheme: default
        primary: indigo
        accent: indigo
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode
      - scheme: slate
        primary: indigo
        accent: indigo
        toggle:
          icon: material/brightness-4
          name: Switch to light mode
    features:
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.top
markdown_extensions:
  - footnotes
  - fenced_code
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.snippets:
      auto_append: ["overrides/contact.md"]
      check_paths: true
  - toc:
      permalink: true
plugins:
  - search:
      separator: '[\s\u200b\-]'
  - mike: {}
  - i18n:
      default_language: zh
      languages:
        en:
          name: English
          site_name: Kube-OVN Document
        zh:
          name: 简体中文
          site_name: Kube-OVN 文档
      nav_translations:
        en:
          主页: OVERVIEW
          快速入门: GETTING STARTED
          使用指南: USER GUIDE
          运维指南: OPERATIONS
          高级功能: ADVANCED USAGE
          技术参考: REFERENCE
          联系方式: CONTACT US
          准备工作: Prerequisites
          一键安装: One-Click Installation
          Underlay 网络安装: Underlay Installation
          卸载: Uninstall
          安装和配置选项: Installation and Configuration Options
          固定地址: Fixed Addresses
          子网使用: Config Subnet
          LoadBalancer 类型 Service: LoadBalancer Type Service
          VPC 使用: Config VPC
          容器网络 QoS 配置: Manage QoS
          配置监控和面板: Monitor and Dashboard
          双栈使用: DualStack
          EIP 和 SNAT 配置: EIP and SNAT
          流量镜像: Traffic Mirror
          NetworkPolicy 日志: NetworkPolicy Logging
          Webhook 使用: Webhook
          kubectl 插件使用: Kubectl Plugin
          删除工作节点: Deleting Work Node
          更换 ovn-central 节点: Replace ovn-central Node
          OVN 数据库备份和恢复: OVN DB Backup and Recovery
          修改子网 CIDR: Change Subnet CIDR
          修改 Join 子网 CIDR: Change Join Subnet CIDR
          卸载 Calico 安装 Kube-OVN: Install Kube-OVN From Calico
          其他常见问题: FAQ
          多网卡管理: Manage Multiple Interface
          性能调优: Performance Tuning
          手动编译 FastPath 模块: Compile FastPath Module
          使用 OVN-IC 进行多集群互联: Cluster Inter-Connection with OVN-IC
          使用 Submariner 进行多集群互联: Cluster Inter-Connection with Submariner
          BGP 支持: BGP Support
          Cilium 集成: Integration with Cilium
          DHCP 设置: DHCP
          VPC 互联: VPC Peering
          外部网关设置: External Gateway
          VIP 预留设置: VIP Reservation
          Mellanox 网卡 Offload 支持: Offload with Mellanox
          芯启源网卡 Offload 支持: Offload with Corigine
          Windows 支持: Windows Support
          DPDK 支持: DPDK Support
          OpenStack 集成: Integration with OpenStack
          总体架构: Architecture
          Underlay 流量拓扑: Underlay Traffic Topology
          开发环境构建: Development Setup
          对上游 OVS/OVN 修改: OVS/OVN Customization
          隧道协议说明: Tunnel Protocol Selection
          Kube-OVN 监控指标: Metrics
          Overlay 下路由方式网络打通: Interconnection with Routes in Overlay Mode
          文档规范: Document Convention
  - git-revision-date-localized:
      type: date
      enable_creation_date: true
  - minify:
      minify_html: true
      htmlmin_opts:
        remove_comments: true
  - markdownextradata: {}
#  - with-pdf:
#      author: Kube-OVN Team
#      cover_subtitle: v1.10.3
extra:
  version:
    provider: mike
    default: stable
  social:
    - icon: fontawesome/brands/weixin
      link: http://page.alauda.cn/kubeovn
    - icon: fontawesome/brands/slack
      link: https://kube-ovn-slackin.herokuapp.com/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/kubeovn
    - icon: fontawesome/brands/github
      link: https://github.com/kubeovn
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/kubeovn/kube-ovn
  variables:
    version: v1.11.0
    branch: release-1.10
copyright: Copyright &copy; 2022 The Linux Foundation
