site_name: Kube-OVN 文档
site_author: Kube-OVN Team
repo_name: kubeovn/kube-ovn
site_url: https://kubeovn.github.io/docs/
repo_url: https://github.com/kubeovn/kube-ovn/
edit_uri: ../docs/edit/master/docs/
nav:
  - 主页: "index.md"
  - 快速入门:
      - 准备工作: "start/prepare.md"
      - 一键安装: "start/one-step-install.md"
      - Underlay 安装: "start/underlay.md"
      - Talos 安装: "start/talos-install.md"
      - 卸载: "start/uninstall.md"
  - 使用指南:
      - 安装和配置选项: "guide/setup-options.md"
      - 子网使用: "guide/subnet.md"
      - 双栈使用: "guide/dual-stack.md"
      - 固定地址: "guide/static-ip-mac.md"
      - IP 使用: "guide/ip.md"
      - IP 池使用: "guide/ippool.md"
      - 自定义路由: "guide/custom-routes.md"
      - EIP 和 SNAT 配置: "guide/eip-snat.md"
      - 容器网络 QoS 配置: "guide/qos.md"
      - Webhook 使用: "guide/webhook.md"
      - 流量镜像: "guide/mirror.md"
      - NetworkPolicy 日志: "guide/networkpolicy-log.md"
      - LoadBalancer 类型 Service: "guide/loadbalancer-service.md"
      - 配置监控和面板: "guide/prometheus-grafana.md"
      - 配置原生 Prometheus: "guide/prometheus.md"
  - KubeVirt:
      - 固定 VM IP: "kubevirt/static-ip.md"
      - VM 使用双栈网络: "kubevirt/dual-stack.md"
      - 热迁移: "kubevirt/live-migration.md"
      - 自定义 DHCP: "kubevirt/dhcp.md"
  - VPC 网络:
      - VPC 入门: "vpc/vpc.md"
      - Egress Gateway: "vpc/vpc-egress-gateway.md"
      - Egress QoS 配置: "vpc/vpc-qos.md"
      - 内部负载均衡: "vpc/vpc-internal-lb.md"
      - 内部 DNS: "vpc/vpc-internal-dns.md"
      - 安全组: "vpc/security-group.md"
      - OVN EIP FIP SNAT 支持: "vpc/ovn-eip-fip-snat.md"
      - OVN SNAT 基于 ECMP BFD 静态路由的 L3 HA 支持: "vpc/ovn-l3-ha-based-ecmp-with-bfd.md"
      - VPC 互联: "vpc/vpc-peering.md"
  - 运维指南:
      - Kubectl 插件使用: "ops/kubectl-ko.md"
      - 删除工作节点: "ops/delete-worker-node.md"
      - 更换 ovn-central 节点: "ops/change-ovn-central-node.md"
      - OVN 数据库备份和恢复: "ops/recover-db.md"
      - 修改子网 CIDR: "ops/change-default-subnet.md"
      - 修改 Join 子网 CIDR: "ops/change-join-subnet.md"
      - 卸载 Calico 安装 Kube-OVN: "ops/from-calico.md"
      - 调整日志等级: "ops/change-log-level.md"
      - 其他常见问题: "ops/faq.md"
  - 高级功能:
      - 多网卡管理: "advance/multi-nic.md"
      - 性能调优: "advance/performance-tuning.md"
      - 手动编译 FastPath 模块: "advance/fastpath.md"
      - 使用 eBPF 加速节点内 TCP 通信: "advance/accelerate-intra-node-tcp-with-ebpf.md"
      - 使用 OVN-IC 进行多集群互联: "advance/with-ovn-ic.md"
      - 使用 Submariner 进行多集群互联: "advance/with-submariner.md"
      - Overlay 下路由方式网络打通: "advance/overlay-with-route.md"
      - BGP 支持: "advance/with-bgp.md"
      - 使用 MetalLB 与 Kube-OVN Underlay 集成: "advance/with-metallb.md"
      - Cilium 集成: "advance/with-cilium.md"
      - Cilium NetworkPolicy 支持: "advance/cilium-networkpolicy.md"
      - Cilium 网络流量观测: "advance/cilium-hubble-observe.md"
      - 外部网关设置: "advance/external-gateway.md"
      - VIP 预留设置: "advance/vip.md"
      - Mellanox 网卡 Offload 支持: "advance/offload-mellanox.md"
      - 芯启源网卡 Offload 支持: "advance/offload-corigine.md"
      - 云脉芯联网卡 Offload 支持: "advance/offload-yunsilicon.md"
      - 中科驭数网卡 Offload 支持: "advance/offload-yusur.md"
      - Windows 支持: "advance/windows.md"
      - DPDK 支持: "advance/dpdk.md"
      - OpenStack 集成: "advance/with-openstack.md"
      - OVN IPsec 支持: "advance/ovn-ipsec.md"
      - OVN 流量镜像: "advance/ovn-remote-port-mirroring.md"
      - 节点本地 DNS 缓存和 Kube-OVN 适配: "advance/node-local-dns.md"
      - 默认 VPC NAT 策略规则: "advance/nat-policy-rule.md"
  - 技术参考:
      - 总体架构: "reference/architecture.md"
      - Roadmap: "reference/roadmap.md"
      - 版本管理: "reference/releasing.md"
      - 功能成熟度: "reference/feature-stage.md"
      - Underlay 流量拓扑: "reference/underlay-topology.md"
      - Iptables 规则: "reference/iptables-rules.md"
      - kube-ovn-pinger 参数描述: "reference/kube-ovn-pinger-args.md"
      - 开发环境构建: "reference/dev-env.md"
      - 对上游 OVS/OVN 修改: "reference/ovs-ovn-customized.md"
      - 隧道协议说明: "reference/tunnel-protocol.md"
      - Kube-OVN 监控指标: "reference/metrics.md"
      - Kube-OVN 接口规范: "reference/kube-ovn-api.md"
      - Annotation 使用说明: "reference/annotations.md"
      - 文档规范: "reference/document-convention.md"
  - 联系方式: "contact.md"
theme:
  logo: static/kube-ovn-icon-color.svg
  favicon: static/kube-ovn-icon-color.svg
  font:
    text: Roboto
  name: material
  custom_dir: overrides
  language: "zh"
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.action.edit
    - content.action.view
markdown_extensions:
  - admonition
  - footnotes
  - fenced_code
  - attr_list
  - sane_lists
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets:
      auto_append: ["overrides/contact.md"]
      check_paths: true
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - social
  - search:
      separator: '[\s\u200b\-]'
  - mike: {}
  - i18n:
      languages:
        - locale: en
          name: English
          site_name: Kube-OVN Document
          nav_translations:
            主页: Overview
            快速入门: Getting Started
            使用指南: User Guide
            运维指南: Operations
            高级功能: Advanced Features
            技术参考: Reference
            联系方式: Contact Us
            准备工作: Prerequisites
            一键安装: One-Click Installation
            Underlay 安装: Underlay Installation
            卸载: Uninstall
            安装和配置选项: Installation and Configuration Options
            固定地址: Fixed Addresses
            IP 使用: Configure IP
            IP 池使用: Configure IPPool
            自定义路由: Custom Routes
            子网使用: Config Subnet
            LoadBalancer 类型 Service: LoadBalancer Type Service
            VPC 网络: VPC Network
            固定 VM IP: Fixed VM IP
            VM 使用双栈网络: VM Use DualStack Network
            热迁移: Live Migration
            自定义 DHCP: Custom DHCP
            VPC 入门: VPC Introduction
            Egress Gateway: Egress Gateway
            Egress QoS 配置: Egress QoS Configuration
            VPC 使用: Config VPC
            VPC QoS 配置: VPC QoS
            容器网络 QoS 配置: Manage QoS
            配置监控和面板: Monitor and Dashboard
            双栈使用: DualStack
            EIP 和 SNAT 配置: EIP and SNAT
            OVN EIP FIP SNAT 支持: Support OVN EIP,FIP and SNAT
            OVN SNAT 基于 ECMP BFD 静态路由的 L3 HA 支持: Support OVN SNAT L3 HA Based ECMP and BFD Static Route
            流量镜像: Traffic Mirror
            NetworkPolicy 日志: NetworkPolicy Logging
            Webhook 使用: Webhook
            Kubectl 插件使用: Kubectl Plugin
            删除工作节点: Deleting Work Node
            更换 ovn-central 节点: Replace ovn-central Node
            OVN 数据库备份和恢复: OVN DB Backup and Recovery
            修改子网 CIDR: Change Subnet CIDR
            修改 Join 子网 CIDR: Change Join Subnet CIDR
            卸载 Calico 安装 Kube-OVN: Install Kube-OVN From Calico
            其他常见问题: FAQ
            多网卡管理: Manage Multiple Interface
            性能调优: Performance Tuning
            手动编译 FastPath 模块: Compile FastPath Module
            使用 eBPF 加速节点内 TCP 通信: Accelerate TCP Communication in Node with eBPF
            使用 OVN-IC 进行多集群互联: Cluster Inter-Connection with OVN-IC
            使用 Submariner 进行多集群互联: Cluster Inter-Connection with Submariner
            BGP 支持: BGP Support
            使用 MetalLB 与 Kube-OVN Underlay 集成: Integrating MetalLB with Kube-OVN Underlay
            Cilium 集成: Integration with Cilium
            Cilium NetworkPolicy 支持: Cilium NetworkPolicy Support
            Cilium 网络流量观测: Cilium Network Traffic Observation
            DHCP 设置: DHCP
            VPC 互联: VPC Peering
            外部网关设置: External Gateway
            VIP 预留设置: VIP Reservation
            Mellanox 网卡 Offload 支持: Offload with Mellanox
            芯启源网卡 Offload 支持: Offload with Corigine
            云脉芯联网卡 Offload 支持: Offload with Yunsilicon
            中科驭数网卡 Offload 支持: Offload with YUSUR
            Windows 支持: Windows Support
            DPDK 支持: DPDK Support
            OpenStack 集成: Integration with OpenStack
            总体架构: Architecture
            Underlay 流量拓扑: Underlay Traffic Topology
            开发环境构建: Development Setup
            对上游 OVS/OVN 修改: OVS/OVN Customization
            隧道协议说明: Tunnel Protocol Selection
            Kube-OVN 监控指标: Metrics
            Overlay 下路由方式网络打通: Interconnection with Routes in Overlay Mode
            文档规范: Document Convention
            功能成熟度: Feature Stage
            配置原生 Prometheus: Config Native Prometheus
            Iptables 规则: Iptables Rules
            kube-ovn-pinger 参数描述: kube-ovn-pinger args description
            内部负载均衡: Internal Load Balancer
            内部 DNS: Internal DNS
            Kube-OVN 接口规范: Kube-OVN API Reference
            SecurityGroup 使用: SecurityGroup Usage
            OVN IPsec 支持: OVN IPsec Support
            OVN 流量镜像: OVN Remote Port Mirroring
            节点本地 DNS 缓存和 Kube-OVN 适配: Node Local DNS Cache and Kube-OVN Adaptation
            默认 VPC NAT 策略规则: Default VPC NAT Policy Rule
            调整日志等级: Change Log Level
            Talos 安装: Install on Talos
            版本管理: Release Management
            Annotation 使用说明: Annotation Usage
            VM 固定 IP: Fixed VM IP
            安全组: Security Group
        - locale: zh
          default: true
          name: 简体中文
          site_name: Kube-OVN 文档
  - git-revision-date-localized:
      type: date
      enable_creation_date: true
  - git-committers:
      repository: kubeovn/docs
  - minify:
      minify_html: true
      htmlmin_opts:
        remove_comments: true
  - markdownextradata: {}
#  - with-pdf:
#      author: Kube-OVN Team
#      cover_subtitle: v1.10.3
extra:
  version:
    provider: mike
    default: stable
  social:
    - icon: fontawesome/brands/weixin
      link: https://jinshuju.net/f/lyrEow
    - icon: fontawesome/brands/slack
      link: https://communityinviter.com/apps/kube-ovn/kube-ovn/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/kubeovn
    - icon: fontawesome/brands/github
      link: https://github.com/kubeovn
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/kubeovn/kube-ovn
  variables:
    version: v1.13.12
    branch: release-1.13
copyright:
  <p>The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation,
  please see our <a href="https://www.linuxfoundation.org/legal/trademark-usage">Trademark Usage page</a>.
  </p>
